// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:1d47a8ec-c8ef-4b43-8bd8-9d6827a434cc',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'visual-hosting-mobilehub-2093290727',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1v0puj7jk4nlg.cloudfront.net',
    'aws_mobile_analytics_app_id': '358874de5a1e4e20a2647a6734f6f355',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '6aaa1701-d9c0-4ead-bf9e-cc37b4faf9de',
    'aws_project_name': 'visual-2018-07-30-09-33-34',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'visual-mobilehub-2093290727',
}

export default awsmobile;
